[package]
name = "ricochet_web"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
ricochet_compiler = { path = "../ricochet_compiler" }
ricochet_syntax = { path = "../ricochet_syntax" }
ricochet_vm = { path = "../ricochet_vm" }
anyhow.workspace = true
axum.workspace = true
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
tokio-postgres.workspace = true
toml.workspace = true
tower.workspace = true
