[package]
name = "ricochet_web"
edition.workspace = true
version.workspace = true
license.workspace = true

[dependencies]
ricochet_bytecode = { path = "../ricochet_bytecode" }
ricochet_compiler = { path = "../ricochet_compiler" }
ricochet_syntax = { path = "../ricochet_syntax" }
ricochet_vm = { path = "../ricochet_vm" }
anyhow.workspace = true
axum.workspace = true
bytes.workspace = true
chacha20poly1305.workspace = true
getrandom.workspace = true
hmac.workspace = true
mysql_async.workspace = true
reqwest.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
tokio.workspace = true
tokio-postgres.workspace = true
toml.workspace = true
tower.workspace = true
