[package]
name = "ricochet_cli"
edition.workspace = true
version.workspace = true
license.workspace = true
autobins = false

[[bin]]
name = "rco"
path = "src/bin/rco.rs"

[[bin]]
name = "ricochet"
path = "src/bin/ricochet.rs"

[[bin]]
name = "rco-gui"
path = "src/bin/rco_gui.rs"

[dependencies]
ricochet_bytecode = { path = "../ricochet_bytecode" }
ricochet_compiler = { path = "../ricochet_compiler" }
ricochet_sandbox = { path = "../ricochet_sandbox" }
ricochet_syntax = { path = "../ricochet_syntax" }
ricochet_vm = { path = "../ricochet_vm" }
ricochet_web = { path = "../ricochet_web" }
anyhow.workspace = true
axum = { workspace = true, features = ["multipart"] }
bytes.workspace = true
chrono.workspace = true
clap.workspace = true
flate2.workspace = true
getrandom.workspace = true
reqwest.workspace = true
rusqlite.workspace = true
serde.workspace = true
serde_json.workspace = true
semver.workspace = true
sha2.workspace = true
spdx.workspace = true
tar.workspace = true
tempfile.workspace = true
tokio.workspace = true
tokio-stream.workspace = true
toml.workspace = true
toml_edit.workspace = true
tower.workspace = true

[dev-dependencies]
tungstenite.workspace = true

[target.'cfg(any(windows, target_os = "linux", target_os = "macos"))'.dependencies]
muda = "0.19.3"
tao = "0.35.3"
wry = "0.55.1"

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_UI_WindowsAndMessaging"] }
