; Exact files shipped by rc.4 but retired from the rc.5 product surface.
; This include runs only after the installer verifies an owned Ricochet install.
Delete "$INSTDIR\rco-app.exe"
Delete "$INSTDIR\packages\ricochet_slint\README.md"
Delete "$INSTDIR\packages\ricochet_slint\backend.rco"
Delete "$INSTDIR\packages\ricochet_slint\ricochet.toml"
Delete "$INSTDIR\packages\ricochet_slint\tests\SlintBackendPackageTest.rco"
Delete "$INSTDIR\packages\ricochet_ui\README.md"
Delete "$INSTDIR\packages\ricochet_ui\commands.rco"
Delete "$INSTDIR\packages\ricochet_ui\document.rco"
Delete "$INSTDIR\packages\ricochet_ui\events.rco"
Delete "$INSTDIR\packages\ricochet_ui\examples\counter_app.rco"
Delete "$INSTDIR\packages\ricochet_ui\examples\data_grid_viewer.rco"
Delete "$INSTDIR\packages\ricochet_ui\examples\native_showcase_app.rco"
Delete "$INSTDIR\packages\ricochet_ui\examples\project_tree_drag_drop.rco"
Delete "$INSTDIR\packages\ricochet_ui\examples\rich_text_note.rco"
Delete "$INSTDIR\packages\ricochet_ui\rich_text.rco"
Delete "$INSTDIR\packages\ricochet_ui\ricochet.toml"
Delete "$INSTDIR\packages\ricochet_ui\tests\UiDocumentPackageTest.rco"
Delete "$INSTDIR\packages\ricochet_ui\tests\UiInteractionPackageTest.rco"
Delete "$INSTDIR\packages\ricochet_ui\tests\UiValidationPackageTest.rco"
Delete "$INSTDIR\packages\ricochet_ui\validation.rco"
Delete "$INSTDIR\packages\ricochet_winui\README.md"
Delete "$INSTDIR\packages\ricochet_winui\backend.rco"
Delete "$INSTDIR\packages\ricochet_winui\ricochet.toml"
Delete "$INSTDIR\packages\ricochet_winui\tests\WinuiBackendPackageTest.rco"

; Remove only directories made empty by the exact deletions above.
RMDir "$INSTDIR\packages\ricochet_slint\tests"
RMDir "$INSTDIR\packages\ricochet_slint"
RMDir "$INSTDIR\packages\ricochet_ui\examples"
RMDir "$INSTDIR\packages\ricochet_ui\tests"
RMDir "$INSTDIR\packages\ricochet_ui"
RMDir "$INSTDIR\packages\ricochet_winui\tests"
RMDir "$INSTDIR\packages\ricochet_winui"
