#!/usr/bin/env bash
set -euo pipefail

generated="${RICOCHET_LINUX_GPG_HOME_GENERATED:-false}"
gnupg_home="${GNUPGHOME:-}"

if [[ "$generated" != "true" || -z "$gnupg_home" ]]; then
  echo "Linux GPG cleanup skipped; GNUPGHOME was not generated by Ricochet setup."
  exit 0
fi

case "$gnupg_home" in
  */ricochet-linux-gnupg.*) ;;
  *)
    echo "Refusing to remove unexpected GNUPGHOME: $gnupg_home" >&2
    exit 1
    ;;
esac

if [[ -d "$gnupg_home" ]]; then
  rm -rf -- "$gnupg_home"
  echo "Removed generated Linux GNUPGHOME."
else
  echo "Generated Linux GNUPGHOME was already absent."
fi
