mod case;
mod harness;

pub use case::{
    AuditExpectation, AvailabilityProbe, CompatibilityProbe, ConformanceCase, ConformanceLevel,
    ExecutableProbe, ExpectedDestination, ExpectedOutcome, ExpectedSessionAudit,
    ExpectedToolFingerprint, FilesystemProbe, HostResourceProbe, IsolationProbe, LifecycleProbe,
    NetworkProbe, ObservedOutcome, PolicyProbe, ProbeAttempt, ProbeKind, ProbeObservation,
    ProbeStatus,
};
pub use harness::{
    run_shared_conformance, ConformanceAttestation, ConformanceDriver, ConformanceReport,
    MockConformanceDriver, ProbeResult,
};

use crate::{
    ExecutionAccess, ExecutionSurface, OperatingSystem, ResourceLimitKind, ResourceLimits,
    SandboxErrorCode, TerminationReason,
};

const READ: &[ExecutionAccess] = &[ExecutionAccess::Read];
const WORKSPACE: &[ExecutionAccess] = &[ExecutionAccess::Workspace];
const FULL: &[ExecutionAccess] = &[ExecutionAccess::Full];
const READ_WORKSPACE: &[ExecutionAccess] = &[ExecutionAccess::Read, ExecutionAccess::Workspace];
const ALL_PLATFORMS: &[OperatingSystem] = &[
    OperatingSystem::Windows,
    OperatingSystem::Linux,
    OperatingSystem::Macos,
];
const WINDOWS: &[OperatingSystem] = &[OperatingSystem::Windows];
const LINUX: &[OperatingSystem] = &[OperatingSystem::Linux];
const MACOS: &[OperatingSystem] = &[OperatingSystem::Macos];
const PROCESS: &[ExecutionSurface] = &[ExecutionSurface::Process];
const BOTH_SURFACES: &[ExecutionSurface] = &[ExecutionSurface::Process, ExecutionSurface::Pty];

const NO_HELPERS: &[&str] = &[];
const ROOT_HELPERS: &[&str] = &["approved-helper"];
const CONSTRAINED_TOOLS: &[ExpectedToolFingerprint] = &[
    ExpectedToolFingerprint {
        tool_id: "approved-helper",
        sha256_hex: "2222222222222222222222222222222222222222222222222222222222222222",
        helper_ids: NO_HELPERS,
    },
    ExpectedToolFingerprint {
        tool_id: "approved-root",
        sha256_hex: "1111111111111111111111111111111111111111111111111111111111111111",
        helper_ids: ROOT_HELPERS,
    },
];
const CONSTRAINED_DESTINATIONS: &[ExpectedDestination] = &[ExpectedDestination {
    host: "sandbox.example",
    port: 443,
}];

const fn constrained_audit() -> AuditExpectation {
    AuditExpectation::Session(ExpectedSessionAudit {
        catalog_generation: 7,
        tools: CONSTRAINED_TOOLS,
        destinations: CONSTRAINED_DESTINATIONS,
        resource_limits: Some(ResourceLimits {
            descendant_processes: 4,
            memory_bytes: 64 * 1024 * 1024,
            cpu_time_ms: 10_000,
            wall_time_ms: 5_000,
            open_descriptors_or_handles: 64,
            captured_output_bytes: 4_096,
        }),
    })
}

const fn full_audit() -> AuditExpectation {
    AuditExpectation::Session(ExpectedSessionAudit {
        catalog_generation: 7,
        tools: &[],
        destinations: &[],
        resource_limits: None,
    })
}

#[allow(clippy::too_many_arguments)]
const fn case(
    id: &'static str,
    level: ConformanceLevel,
    probe: ProbeKind,
    accesses: &'static [ExecutionAccess],
    platforms: &'static [OperatingSystem],
    surfaces: &'static [ExecutionSurface],
    expected: ExpectedOutcome,
    expected_audit: AuditExpectation,
) -> ConformanceCase {
    ConformanceCase {
        id,
        level,
        probe,
        accesses,
        platforms,
        surfaces,
        expected,
        expected_audit,
    }
}

static SHARED_CASES: [ConformanceCase; 85] = [
    case(
        "policy.version_rejection",
        ConformanceLevel::Model,
        ProbeKind::Policy(PolicyProbe::VersionRejection),
        READ,
        ALL_PLATFORMS,
        PROCESS,
        ExpectedOutcome::Denied(SandboxErrorCode::BrokerProtocolError),
        AuditExpectation::AbsentBeforeSession,
    ),
    case(
        "policy.unknown_field_rejection",
        ConformanceLevel::Model,
        ProbeKind::Policy(PolicyProbe::UnknownFieldRejection),
        READ,
        ALL_PLATFORMS,
        PROCESS,
        ExpectedOutcome::Denied(SandboxErrorCode::BrokerProtocolError),
        AuditExpectation::AbsentBeforeSession,
    ),
    case(
        "policy.invalid_access_combination",
        ConformanceLevel::Model,
        ProbeKind::Policy(PolicyProbe::InvalidAccessCombination),
        READ,
        ALL_PLATFORMS,
        PROCESS,
        ExpectedOutcome::Denied(SandboxErrorCode::SandboxPolicyError),
        AuditExpectation::AbsentBeforeSession,
    ),
    case(
        "policy.grant_broadening_rejected",
        ConformanceLevel::Model,
        ProbeKind::Policy(PolicyProbe::GrantBroadeningRejected),
        READ,
        ALL_PLATFORMS,
        PROCESS,
        ExpectedOutcome::Denied(SandboxErrorCode::SandboxPolicyError),
        AuditExpectation::AbsentBeforeSession,
    ),
    case(
        "policy.grant_narrowing_allowed",
        ConformanceLevel::Model,
        ProbeKind::Policy(PolicyProbe::GrantNarrowingAllowed),
        READ,
        ALL_PLATFORMS,
        PROCESS,
        ExpectedOutcome::Allowed,
        AuditExpectation::AbsentBeforeSession,
    ),
    case(
        "policy.catalog_closure",
        ConformanceLevel::Model,
        ProbeKind::Policy(PolicyProbe::CatalogClosure),
        READ,
        ALL_PLATFORMS,
        PROCESS,
        ExpectedOutcome::Allowed,
        AuditExpectation::AbsentBeforeSession,
    ),
    case(
        "policy.fingerprint_mismatch",
        ConformanceLevel::Model,
        ProbeKind::Policy(PolicyProbe::FingerprintMismatch),
        READ,
        ALL_PLATFORMS,
        PROCESS,
        ExpectedOutcome::Denied(SandboxErrorCode::ToolFingerprintMismatch),
        AuditExpectation::AbsentBeforeSession,
    ),
    case(
        "policy.revocation",
        ConformanceLevel::Model,
        ProbeKind::Policy(PolicyProbe::Revocation),
        READ,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::TerminatesTree {
            reason: TerminationReason::ToolRevoked,
        },
        constrained_audit(),
    ),
    case(
        "policy.environment_redaction",
        ConformanceLevel::Model,
        ProbeKind::Policy(PolicyProbe::EnvironmentRedaction),
        READ,
        ALL_PLATFORMS,
        PROCESS,
        ExpectedOutcome::Allowed,
        AuditExpectation::AbsentBeforeSession,
    ),
    case(
        "policy.process_pty_parity",
        ConformanceLevel::Model,
        ProbeKind::Policy(PolicyProbe::ProcessPtyParity),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Allowed,
        constrained_audit(),
    ),
    case(
        "policy.lifecycle_ordering",
        ConformanceLevel::Model,
        ProbeKind::Policy(PolicyProbe::LifecycleOrdering),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Allowed,
        constrained_audit(),
    ),
    case(
        "policy.complete_tree_cancellation",
        ConformanceLevel::Model,
        ProbeKind::Policy(PolicyProbe::CompleteTreeCancellation),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Allowed,
        constrained_audit(),
    ),
    case(
        "policy.mock_honesty",
        ConformanceLevel::Model,
        ProbeKind::Policy(PolicyProbe::MockHonesty),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Allowed,
        constrained_audit(),
    ),
    case(
        "filesystem.workspace_read_allowed",
        ConformanceLevel::RealOs,
        ProbeKind::Filesystem(FilesystemProbe::WorkspaceReadAllowed),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Allowed,
        constrained_audit(),
    ),
    case(
        "filesystem.workspace_write_denied_read",
        ConformanceLevel::RealOs,
        ProbeKind::Filesystem(FilesystemProbe::WorkspaceWriteDeniedRead),
        READ,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "filesystem.workspace_write_allowed",
        ConformanceLevel::RealOs,
        ProbeKind::Filesystem(FilesystemProbe::WorkspaceWriteAllowed),
        WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Allowed,
        constrained_audit(),
    ),
    case(
        "filesystem.scratch_read_write_allowed",
        ConformanceLevel::RealOs,
        ProbeKind::Filesystem(FilesystemProbe::ScratchReadWriteAllowed),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Allowed,
        constrained_audit(),
    ),
    case(
        "filesystem.outside_read",
        ConformanceLevel::RealOs,
        ProbeKind::Filesystem(FilesystemProbe::OutsideRead),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "filesystem.outside_write",
        ConformanceLevel::RealOs,
        ProbeKind::Filesystem(FilesystemProbe::OutsideWrite),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "filesystem.outside_create",
        ConformanceLevel::RealOs,
        ProbeKind::Filesystem(FilesystemProbe::OutsideCreate),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "filesystem.outside_delete",
        ConformanceLevel::RealOs,
        ProbeKind::Filesystem(FilesystemProbe::OutsideDelete),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "filesystem.outside_rename",
        ConformanceLevel::RealOs,
        ProbeKind::Filesystem(FilesystemProbe::OutsideRename),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "filesystem.outside_link",
        ConformanceLevel::RealOs,
        ProbeKind::Filesystem(FilesystemProbe::OutsideLink),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "filesystem.outside_metadata",
        ConformanceLevel::RealOs,
        ProbeKind::Filesystem(FilesystemProbe::OutsideMetadata),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "filesystem.outside_execute",
        ConformanceLevel::RealOs,
        ProbeKind::Filesystem(FilesystemProbe::OutsideExecute),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "filesystem.symlink_escape",
        ConformanceLevel::RealOs,
        ProbeKind::Filesystem(FilesystemProbe::SymlinkEscape),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "filesystem.junction_escape",
        ConformanceLevel::RealOs,
        ProbeKind::Filesystem(FilesystemProbe::JunctionEscape),
        READ_WORKSPACE,
        WINDOWS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "filesystem.reparse_escape",
        ConformanceLevel::RealOs,
        ProbeKind::Filesystem(FilesystemProbe::ReparseEscape),
        READ_WORKSPACE,
        WINDOWS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "filesystem.hard_link_escape",
        ConformanceLevel::RealOs,
        ProbeKind::Filesystem(FilesystemProbe::HardLinkEscape),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "filesystem.mount_escape",
        ConformanceLevel::RealOs,
        ProbeKind::Filesystem(FilesystemProbe::MountEscape),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "filesystem.descriptor_escape",
        ConformanceLevel::RealOs,
        ProbeKind::Filesystem(FilesystemProbe::DescriptorEscape),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "filesystem.namespace_escape",
        ConformanceLevel::RealOs,
        ProbeKind::Filesystem(FilesystemProbe::NamespaceEscape),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "filesystem.rename_race",
        ConformanceLevel::RealOs,
        ProbeKind::Filesystem(FilesystemProbe::RenameRace),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "host_resource.user_profile",
        ConformanceLevel::RealOs,
        ProbeKind::HostResource(HostResourceProbe::UserProfile),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "host_resource.registry",
        ConformanceLevel::RealOs,
        ProbeKind::HostResource(HostResourceProbe::Registry),
        READ_WORKSPACE,
        WINDOWS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "host_resource.keychain",
        ConformanceLevel::RealOs,
        ProbeKind::HostResource(HostResourceProbe::Keychain),
        READ_WORKSPACE,
        MACOS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "host_resource.proc",
        ConformanceLevel::RealOs,
        ProbeKind::HostResource(HostResourceProbe::Proc),
        READ_WORKSPACE,
        LINUX,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "host_resource.credential_store",
        ConformanceLevel::RealOs,
        ProbeKind::HostResource(HostResourceProbe::CredentialStore),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "host_resource.device",
        ConformanceLevel::RealOs,
        ProbeKind::HostResource(HostResourceProbe::Device),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "host_resource.clipboard",
        ConformanceLevel::RealOs,
        ProbeKind::HostResource(HostResourceProbe::Clipboard),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "host_resource.ipc",
        ConformanceLevel::RealOs,
        ProbeKind::HostResource(HostResourceProbe::Ipc),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "host_resource.inherited_handle",
        ConformanceLevel::RealOs,
        ProbeKind::HostResource(HostResourceProbe::InheritedHandle),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "executable.approved_root_allowed",
        ConformanceLevel::RealOs,
        ProbeKind::Executable(ExecutableProbe::ApprovedRootAllowed),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Allowed,
        constrained_audit(),
    ),
    case(
        "executable.approved_helper_allowed",
        ConformanceLevel::RealOs,
        ProbeKind::Executable(ExecutableProbe::ApprovedHelperAllowed),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Allowed,
        constrained_audit(),
    ),
    case(
        "executable.direct_child",
        ConformanceLevel::RealOs,
        ProbeKind::Executable(ExecutableProbe::DirectChild),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Denied(SandboxErrorCode::ToolNotApproved),
        constrained_audit(),
    ),
    case(
        "executable.grandchild",
        ConformanceLevel::RealOs,
        ProbeKind::Executable(ExecutableProbe::Grandchild),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Denied(SandboxErrorCode::ToolNotApproved),
        constrained_audit(),
    ),
    case(
        "executable.shell_helper",
        ConformanceLevel::RealOs,
        ProbeKind::Executable(ExecutableProbe::ShellHelper),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Denied(SandboxErrorCode::ToolNotApproved),
        constrained_audit(),
    ),
    case(
        "executable.interpreter",
        ConformanceLevel::RealOs,
        ProbeKind::Executable(ExecutableProbe::Interpreter),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Denied(SandboxErrorCode::ToolNotApproved),
        constrained_audit(),
    ),
    case(
        "executable.fingerprint_substitution",
        ConformanceLevel::RealOs,
        ProbeKind::Executable(ExecutableProbe::FingerprintSubstitution),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Denied(SandboxErrorCode::ToolFingerprintMismatch),
        constrained_audit(),
    ),
    case(
        "network.granted_http_adapter_allowed",
        ConformanceLevel::RealOs,
        ProbeKind::Network(NetworkProbe::GrantedHttpAdapterAllowed),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Allowed,
        constrained_audit(),
    ),
    case(
        "network.granted_ssh_adapter_allowed",
        ConformanceLevel::RealOs,
        ProbeKind::Network(NetworkProbe::GrantedSshAdapterAllowed),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Allowed,
        constrained_audit(),
    ),
    case(
        "network.direct_socket",
        ConformanceLevel::RealOs,
        ProbeKind::Network(NetworkProbe::DirectSocket),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "network.adapter_bypass",
        ConformanceLevel::RealOs,
        ProbeKind::Network(NetworkProbe::AdapterBypass),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Denied(SandboxErrorCode::NetworkDenied),
        constrained_audit(),
    ),
    case(
        "network.dns_rebinding",
        ConformanceLevel::RealOs,
        ProbeKind::Network(NetworkProbe::DnsRebinding),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Denied(SandboxErrorCode::NetworkDenied),
        constrained_audit(),
    ),
    case(
        "network.ipv4_literal",
        ConformanceLevel::RealOs,
        ProbeKind::Network(NetworkProbe::Ipv4Literal),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "network.ipv6_literal",
        ConformanceLevel::RealOs,
        ProbeKind::Network(NetworkProbe::Ipv6Literal),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "network.shared_ip",
        ConformanceLevel::RealOs,
        ProbeKind::Network(NetworkProbe::SharedIp),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Denied(SandboxErrorCode::NetworkDenied),
        constrained_audit(),
    ),
    case(
        "network.port_substitution",
        ConformanceLevel::RealOs,
        ProbeKind::Network(NetworkProbe::PortSubstitution),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Denied(SandboxErrorCode::NetworkDenied),
        constrained_audit(),
    ),
    case(
        "network.localhost",
        ConformanceLevel::RealOs,
        ProbeKind::Network(NetworkProbe::Localhost),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "network.private_range",
        ConformanceLevel::RealOs,
        ProbeKind::Network(NetworkProbe::PrivateRange),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "network.udp",
        ConformanceLevel::RealOs,
        ProbeKind::Network(NetworkProbe::Udp),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "network.quic",
        ConformanceLevel::RealOs,
        ProbeKind::Network(NetworkProbe::Quic),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "network.listener",
        ConformanceLevel::RealOs,
        ProbeKind::Network(NetworkProbe::Listener),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "isolation.cross_session_scratch",
        ConformanceLevel::RealOs,
        ProbeKind::Isolation(IsolationProbe::CrossSessionScratch),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "isolation.cross_session_catalog",
        ConformanceLevel::RealOs,
        ProbeKind::Isolation(IsolationProbe::CrossSessionCatalog),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::DeniedBySandbox,
        constrained_audit(),
    ),
    case(
        "lifecycle.timeout_tree",
        ConformanceLevel::RealOs,
        ProbeKind::Lifecycle(LifecycleProbe::TimeoutTree),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::TerminatesTree {
            reason: TerminationReason::TimedOut,
        },
        constrained_audit(),
    ),
    case(
        "lifecycle.cancel_tree",
        ConformanceLevel::RealOs,
        ProbeKind::Lifecycle(LifecycleProbe::CancelTree),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::TerminatesTree {
            reason: TerminationReason::CancelledByHost,
        },
        constrained_audit(),
    ),
    case(
        "lifecycle.revocation_tree",
        ConformanceLevel::RealOs,
        ProbeKind::Lifecycle(LifecycleProbe::RevocationTree),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::TerminatesTree {
            reason: TerminationReason::ToolRevoked,
        },
        constrained_audit(),
    ),
    case(
        "lifecycle.broker_shutdown_tree",
        ConformanceLevel::RealOs,
        ProbeKind::Lifecycle(LifecycleProbe::BrokerShutdownTree),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::TerminatesTree {
            reason: TerminationReason::BrokerShutdown,
        },
        constrained_audit(),
    ),
    case(
        "lifecycle.resource_limit.descendant_processes",
        ConformanceLevel::RealOs,
        ProbeKind::Lifecycle(LifecycleProbe::ResourceLimit(
            ResourceLimitKind::DescendantProcesses,
        )),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::TerminatesTree {
            reason: TerminationReason::ResourceLimit(ResourceLimitKind::DescendantProcesses),
        },
        constrained_audit(),
    ),
    case(
        "lifecycle.resource_limit.memory_bytes",
        ConformanceLevel::RealOs,
        ProbeKind::Lifecycle(LifecycleProbe::ResourceLimit(
            ResourceLimitKind::MemoryBytes,
        )),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::TerminatesTree {
            reason: TerminationReason::ResourceLimit(ResourceLimitKind::MemoryBytes),
        },
        constrained_audit(),
    ),
    case(
        "lifecycle.resource_limit.cpu_time",
        ConformanceLevel::RealOs,
        ProbeKind::Lifecycle(LifecycleProbe::ResourceLimit(ResourceLimitKind::CpuTime)),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::TerminatesTree {
            reason: TerminationReason::ResourceLimit(ResourceLimitKind::CpuTime),
        },
        constrained_audit(),
    ),
    case(
        "lifecycle.resource_limit.wall_time",
        ConformanceLevel::RealOs,
        ProbeKind::Lifecycle(LifecycleProbe::ResourceLimit(ResourceLimitKind::WallTime)),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::TerminatesTree {
            reason: TerminationReason::ResourceLimit(ResourceLimitKind::WallTime),
        },
        constrained_audit(),
    ),
    case(
        "lifecycle.resource_limit.open_descriptors_or_handles",
        ConformanceLevel::RealOs,
        ProbeKind::Lifecycle(LifecycleProbe::ResourceLimit(
            ResourceLimitKind::OpenDescriptorsOrHandles,
        )),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::TerminatesTree {
            reason: TerminationReason::ResourceLimit(ResourceLimitKind::OpenDescriptorsOrHandles),
        },
        constrained_audit(),
    ),
    case(
        "lifecycle.resource_limit.captured_output",
        ConformanceLevel::RealOs,
        ProbeKind::Lifecycle(LifecycleProbe::ResourceLimit(
            ResourceLimitKind::CapturedOutput,
        )),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::TerminatesTree {
            reason: TerminationReason::ResourceLimit(ResourceLimitKind::CapturedOutput),
        },
        constrained_audit(),
    ),
    case(
        "lifecycle.registry_consistency",
        ConformanceLevel::RealOs,
        ProbeKind::Lifecycle(LifecycleProbe::RegistryConsistency),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Allowed,
        constrained_audit(),
    ),
    case(
        "lifecycle.clean_close_scratch_deleted",
        ConformanceLevel::RealOs,
        ProbeKind::Lifecycle(LifecycleProbe::CleanCloseScratchDeleted),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Allowed,
        constrained_audit(),
    ),
    case(
        "lifecycle.crash_scratch_retained",
        ConformanceLevel::RealOs,
        ProbeKind::Lifecycle(LifecycleProbe::CrashScratchRetained),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Allowed,
        constrained_audit(),
    ),
    case(
        "availability.broker_crash",
        ConformanceLevel::RealOs,
        ProbeKind::Availability(AvailabilityProbe::BrokerCrash),
        READ_WORKSPACE,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::TerminatesTree {
            reason: TerminationReason::BrokerShutdown,
        },
        constrained_audit(),
    ),
    case(
        "availability.stale_protocol",
        ConformanceLevel::RealOs,
        ProbeKind::Availability(AvailabilityProbe::StaleProtocol),
        READ,
        ALL_PLATFORMS,
        PROCESS,
        ExpectedOutcome::Unavailable(SandboxErrorCode::BrokerProtocolError),
        AuditExpectation::AbsentBeforeSession,
    ),
    case(
        "availability.partial_installation",
        ConformanceLevel::RealOs,
        ProbeKind::Availability(AvailabilityProbe::PartialInstallation),
        READ,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Unavailable(SandboxErrorCode::SandboxUnavailable),
        AuditExpectation::AbsentBeforeSession,
    ),
    case(
        "availability.inactive_enforcement",
        ConformanceLevel::RealOs,
        ProbeKind::Availability(AvailabilityProbe::InactiveEnforcement),
        READ,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Unavailable(SandboxErrorCode::SandboxUnavailable),
        AuditExpectation::AbsentBeforeSession,
    ),
    case(
        "availability.unsupported_kernel",
        ConformanceLevel::RealOs,
        ProbeKind::Availability(AvailabilityProbe::UnsupportedKernel),
        READ,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Unavailable(SandboxErrorCode::SandboxUnavailable),
        AuditExpectation::AbsentBeforeSession,
    ),
    case(
        "compatibility.full_source_compatibility",
        ConformanceLevel::RealOs,
        ProbeKind::Compatibility(CompatibilityProbe::FullSourceCompatibility),
        FULL,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Allowed,
        full_audit(),
    ),
    case(
        "compatibility.full_audit_truth",
        ConformanceLevel::RealOs,
        ProbeKind::Compatibility(CompatibilityProbe::FullAuditTruth),
        FULL,
        ALL_PLATFORMS,
        BOTH_SURFACES,
        ExpectedOutcome::Allowed,
        full_audit(),
    ),
];

pub fn shared_cases() -> &'static [ConformanceCase] {
    &SHARED_CASES
}
