param(
    [string]$Root = (Split-Path -Parent $MyInvocation.MyCommand.Path)
)

$ErrorActionPreference = "Stop"

$requiredFiles = @(
    "index.html",
    "styles.css",
    "app.js",
    "README.md",
    "guides/index.html",
    "guides/features.html",
    "guides/getting-started.html",
    "guides/language-runtime.html",
    "guides/web-and-data.html",
    "guides/host-capabilities.html",
    "guides/packages.html",
    "guides/editor-debugging.html",
    "guides/development-release.html"
)

$failures = New-Object System.Collections.Generic.List[string]

foreach ($file in $requiredFiles) {
    $path = Join-Path $Root $file
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        $failures.Add("Missing required docs file: $file")
    }
}

if ($failures.Count -eq 0) {
    $index = Get-Content -LiteralPath (Join-Path $Root "index.html") -Raw
    $styles = Get-Content -LiteralPath (Join-Path $Root "styles.css") -Raw
    $app = Get-Content -LiteralPath (Join-Path $Root "app.js") -Raw
    $readme = Get-Content -LiteralPath (Join-Path $Root "README.md") -Raw
    $guidesIndex = Get-Content -LiteralPath (Join-Path $Root "guides/index.html") -Raw
    $webAndDataGuide = Get-Content -LiteralPath (Join-Path $Root "guides/web-and-data.html") -Raw

    $requiredIndexMarkers = @(
        "Ricochet Reference",
        "id=""syntax""",
        "id=""words""",
        "id=""oop""",
        "id=""mvc""",
        "id=""active-record""",
        "id=""turing-complete""",
        "id=""debugging""",
        "id=""cli""",
        "id=""limits""",
        "guides/index.html"
    )

    foreach ($marker in $requiredIndexMarkers) {
        if (-not $index.Contains($marker)) {
            $failures.Add("index.html is missing marker: $marker")
        }
    }

    $requiredGuideMarkers = @(
        "Ricochet Guides",
        "Feature Overview",
        "Getting Started",
        "Language And Runtime",
        "Web And Data",
        "Host Capabilities And Safety",
        "Packages And Registries",
        "Editor And Debugging",
        "Development And Release"
    )

    foreach ($marker in $requiredGuideMarkers) {
        if (-not $guidesIndex.Contains($marker)) {
            $failures.Add("guides/index.html is missing marker: $marker")
        }
    }

    $requiredWords = @(
        '"+"',
        '"add"',
        '"-"',
        '"subtract"',
        '"*"',
        '"/"',
        '"%"',
        '"negate"',
        '"abs"',
        '"min"',
        '"max"',
        '"clamp"',
        '"not"',
        '"and"',
        '"or"',
        '"equals"',
        '"not_equals?"',
        '"assert"',
        '"assert_true"',
        '"assert_false"',
        '"assert_equals"',
        '"assert_ok"',
        '"assert_error"',
        '"less_than?"',
        '"greater_than?"',
        '"less_or_equals?"',
        '"greater_or_equals?"',
        '"self"',
        '"get"',
        '"set"',
        '"var"',
        '"Field"',
        '"Table"',
        '"Subclass"',
        '"new"',
        '"swap"',
        '"dup"',
        '"drop"',
        '"over"',
        '"rot"',
        '"nip"',
        '"tuck"',
        '"pick"',
        '"roll"',
        '"depth"',
        '"clear"',
        '"call"',
        '"spawn"',
        '"await"',
        '"await_all"',
        '"release_task"',
        '"tasks"',
        '"task_status"',
        '"while"',
        '"break"',
        '"continue"',
        '"send"',
        '"println"',
        '"view"',
        '"text"',
        '"json"',
        '"redirect"',
        '"status"',
        '"header"',
        '"value"',
        '"error"',
        '"array"',
        '"list"',
        '"map"',
        '"Set"',
        '"range"',
        '"push!"',
        '"put!"',
        '"push!"',
        '"put!"',
        '"insert!"',
        '"remove!"',
        '"remove_at!"',
        '"clear!"',
        '"count"',
        '"at"',
        '"first"',
        '"last"',
        '"take"',
        '"skip"',
        '"reverse"',
        '"has?"',
        '"keys"',
        '"values"',
        '"each"',
        '"transform"',
        '"select"',
        '"reduce"',
        '"find"',
        '"find_record"',
        '"default_page"',
        '"limit"',
        '"count_records"',
        '"first_record"',
        '"any?"',
        '"all?"',
        '"join"',
        '"trim"',
        '"trim_start"',
        '"trim_end"',
        '"blank?"',
        '"slice"',
        '"index_of"',
        '"last_index_of"',
        '"repeat"',
        '"lines"',
        '"chars"',
        '"split"',
        '"replace"',
        '"contains?"',
        '"starts_with?"',
        '"ends_with?"',
        '"uppercase"',
        '"lowercase"',
        '"concat"',
        '"to_number"',
        '"to_integer"',
        '"to_bigint"',
        '"to_int"',
        '"to_mediumint"',
        '"to_smallint"',
        '"to_tinyint"',
        '"to_bit"',
        '"to_unsigned_int"',
        '"to_unsigned_mediumint"',
        '"to_unsigned_smallint"',
        '"to_unsigned_tinyint"',
        '"to_unsigned_bigint"',
        '"to_float"',
        '"to_float32"',
        '"to_float64"',
        '"to_double"',
        '"to_real"',
        '"to_string"',
        '"json_encode"',
        '"json_decode"',
        '"regex"',
        '"matches?"',
        '"regex_find"',
        '"regex_replace"',
        '"captures"',
        '"Method"',
        '"ok?"',
        '"ok"',
        '"fail"',
        '"error?"',
        '"unwrap_or"',
        '"map_result"',
        '"and_then"',
        '"result_envelope"',
        '"nil?"',
        '"empty?"',
        '"print"',
        '"eprint"',
        '"read_line"',
        '"args"',
        '"env_get"',
        '"env"',
        '"env_set"',
        '"secret_env"',
        '"secret_literal"',
        '"secret_resolve"',
        '"password_hash"',
        '"password_verify"',
        '"upload_streams"',
        '"upload_stream"',
        '"upload_read"',
        '"upload_release"',
        '"config_get"',
        '"cwd"',
        '"runtime_capabilities"',
        '"info"',
        '"process_spawn"',
        '"process_spawn_task"',
        '"process_start"',
        '"process_jobs"',
        '"process_job"',
        '"process_cancel"',
        '"process_release"',
        '"process_read"',
        '"process_env_put"',
        '"pty_start"',
        '"pty_write"',
        '"pty_read"',
        '"pty_resize"',
        '"pty_stop"',
        '"pty_release"',
        '"pty_list"',
        '"pty_detail"',
        '"approval_create"',
        '"approval_claim"',
        '"approval_complete"',
        '"approval_reject"',
        '"approval_detail"',
        '"now"',
        '"timestamp_now"',
        '"timestamp_parse"',
        '"timestamp_format"',
        '"timestamp_format_pattern"',
        '"timestamp_parts"',
        '"timestamp_from_parts"',
        '"timestamp_add"',
        '"timestamp_diff"',
        '"date_from_timestamp"',
        '"date_to_timestamp"',
        '"date_parse"',
        '"date_format"',
        '"date_add_days"',
        '"date_diff_days"',
        '"duration_millis"',
        '"duration_seconds"',
        '"duration_minutes"',
        '"duration_hours"',
        '"duration_days"',
        '"duration_weeks"',
        '"duration_parts"',
        '"sleep"',
        '"random"',
        '"exit"',
        '"fs_read_text"',
        '"fs_write_text"',
        '"fs_exists?"',
        '"fs_list"',
        '"fs_create_dir"',
        '"fs_delete"',
        '"workspace_resolve"',
        '"workspace_contains?"',
        '"workspace_metadata"',
        '"workspace_list"',
        '"workspace_read_text"',
        '"workspace_write_text"',
        '"workspace_mkdir"',
        '"workspace_delete"',
        '"workspace_copy"',
        '"workspace_move"',
        '"http_request_new"',
        '"http_header_put"',
        '"http_bearer_auth"',
        '"http_json_body"',
        '"http_timeout"',
        '"http_get"',
        '"http_get_task"',
        '"http_request"',
        '"http_post_json"',
        '"http_post_json_task"',
        '"http_request_task"',
        '"tcp_listen"',
        '"tcp_listeners"',
        '"tcp_listener"',
        '"tcp_accept"',
        '"tcp_listener_close"',
        '"tcp_listener_release"',
        '"tcp_connect"',
        '"tcp_connections"',
        '"tcp_connection"',
        '"tcp_write"',
        '"tcp_read"',
        '"tcp_close"',
        '"tcp_release"',
        '"ws_listen"',
        '"ws_listeners"',
        '"ws_listener"',
        '"ws_accept"',
        '"ws_listener_close"',
        '"ws_listener_release"',
        '"ws_connect"',
        '"ws_connections"',
        '"ws_connection"',
        '"ws_send"',
        '"ws_read"',
        '"ws_close"',
        '"ws_release"',
        '"tui_enter"',
        '"tui_leave"',
        '"tui_move_to"',
        '"tui_write"',
        '"tui_flush"',
        '"tui_size"',
        '"tui_poll_key"',
        '"tui_read_key"',
        '"webview_text"',
        '"webview_heading"',
        '"webview_button"',
        '"webview_action"',
        '"webview_input"',
        '"webview_link"',
        '"webview_container"',
        '"webview_window"',
        '"webview_window_state"',
        '"webview_document"',
        '"inspect"',
        '"debug"',
        '"type"',
        '"class_of"',
        '"instance_of?"',
        '"responds_to?"',
        '"id"',
        '"status"',
        '"pending?"',
        '"fields"',
        '"methods"',
        '"callable?"'
    )

    foreach ($word in $requiredWords) {
        if (-not $app.Contains($word)) {
            $failures.Add("app.js is missing reference entry for: $word")
        }
    }

    $requiredExamples = @(
        "User Model Subclass",
        "HomeController Controller Subclass",
        'GET "/" HomeController "index" route',
        "User all",
        "42 User find_record",
        "10 User limit",
        "User count_records",
        "User first_record",
        "1 User exists?",
        "users array",
        "settings map",
        "tags Set",
        "push!",
        "put!",
        "slice",
        "regex value",
        "[web.static]",
        "mount = `"/assets`"",
        "User Model Subclass",
        "`$count 10 < while",
        "rco run --debug --step app.rco",
        "rco debug --json app.rco",
        "rco debug-adapter",
        "rco run --trace-file trace.json app.rco",
        "step``, ``next``, ``out``, ``continue``",
        "``self``, or ``tasks``",
        "rco fmt [--check] [path]",
        "rco lint [--json] [path]",
        "rco run [--debug] [--step] [--breakpoint LINE] [--trace-file PATH] [--capability-profile trusted|sandboxed] [--no-fs] [--fs-root PATH] [--fs-readonly] [--no-http] [--allow-process] [--process-root PATH] [--allow-pty] [--no-tui] [--allow-tui] [--no-webview] [--allow-webview] [--no-env] [--env-allow NAME] [--no-sleep] [--http-allow-host HOST] [--allow-sockets] [--socket-allow-host HOST] &lt;path&gt; [args...]",
        "rco debug [--json] [--step] [--breakpoint LINE] [--trace-file PATH] [--capability-profile trusted|sandboxed] [--no-fs] [--fs-root PATH] [--fs-readonly] [--no-http] [--allow-process] [--process-root PATH] [--allow-pty] [--no-tui] [--allow-tui] [--no-webview] [--allow-webview] [--no-env] [--env-allow NAME] [--no-sleep] [--http-allow-host HOST] [--allow-sockets] [--socket-allow-host HOST] &lt;path&gt; [args...]",
        "rco debug-adapter",
        "rco run-bytecode [--debug] [--trace-file PATH] [--capability-profile trusted|sandboxed] [--no-fs] [--fs-root PATH] [--fs-readonly] [--no-http] [--allow-process] [--process-root PATH] [--allow-pty] [--no-tui] [--allow-tui] [--no-webview] [--allow-webview] [--no-env] [--env-allow NAME] [--no-sleep] [--http-allow-host HOST] [--allow-sockets] [--socket-allow-host HOST] &lt;path&gt; [args...]",
        "rco gui [--capability-profile trusted|sandboxed] [--no-fs] [--fs-root PATH] [--fs-readonly] [--no-http] [--allow-process] [--process-root PATH] [--allow-pty] [--no-tui] [--allow-tui] [--no-webview] [--allow-webview] [--no-env] [--env-allow NAME] [--no-sleep] [--http-allow-host HOST] [--allow-sockets] [--socket-allow-host HOST] &lt;path&gt; [args...]",
        "rco tui [--capability-profile trusted|sandboxed] [--no-fs] [--fs-root PATH] [--fs-readonly] [--no-http] [--allow-process] [--process-root PATH] [--allow-pty] [--no-tui] [--allow-tui] [--no-webview] [--allow-webview] [--no-env] [--env-allow NAME] [--no-sleep] [--http-allow-host HOST] [--allow-sockets] [--socket-allow-host HOST] &lt;path&gt; [args...]",
        "rco package [path] --output &lt;exe&gt; [--tui] [--gui] [--mvc] [--gui-launcher PATH] [--linux-package tar|deb] [--package-name NAME] [--package-version VERSION]",
        "rco add &lt;source&gt; [--name NAME|--as ALIAS] [--registry PATH|--registry-url URL] [--version REQ] [--no-fetch]",
        "rco publish [path] --registry PATH [--provenance-file PATH] [--signature-file PATH] [--signature-kind KIND] [--dry-run]",
        "rco registry rebuild PATH",
        "rco registry check PATH",
        "rco search QUERY [--registry PATH|--registry-url URL]",
        "rco verify [path]",
        "rco audit [path] [--json]",
        "rco doctor [--capabilities] [path]",
        "rco words [--json] [--check] [--docs-app PATH] [--grammar PATH]",
        "rco bench [--iterations N] [--smoke] [--json]",
        "rco lsp-diagnostics [--pretty] &lt;path&gt;",
        "rco migrate new NAME [--dsl] [path]",
        "rco migrate status [path]",
        "rco migrate apply [path]",
        "rco migrate rollback [path] [--steps N]",
        "rco migrate dump [path] [--output PATH]",
        "rco seed [path]",
        "&quot;notes&quot; table_create",
        "&quot;id&quot; &quot;integer&quot; column primary_key",
        "&quot;notes&quot; table_drop",
        "`"lib/math`" import",
        "`"forms/validation`" import",
        "[dependencies.forms]",
        "rco add registry:@ricochet/forms --registry ../ricochet-registry --as forms --version `"^0.1.0`"",
        "rco add registry:@ricochet/forms --registry-url file:///E:/path/to/ricochet-registry/index.toml --as forms --version `"^0.1.0`"",
        "rco registry rebuild ../ricochet-registry",
        "rco registry check ../ricochet-registry",
        "rco search forms --registry-url file:///E:/path/to/ricochet-registry/index.toml",
        "--provenance-file provenance.json --signature-file forms.sig --signature-kind minisign",
        "rco audit --json",
        "rco add github:BARKx4/ricochet_auth@v0.1.0 --no-fetch",
        "`"/dashboard`" redirect",
        "rco routes [path]",
        "rco serve [--host HOST] [--port PORT] [--debug] [--watch] [--allow-env] [--no-env] [--env-allow NAME] [--allow-process] [--process-root PATH] [--allow-pty] [--fs-root PATH] [--fs-readonly] [--http-allow-host HOST]",
        "rco test [--debug] [--filter PATTERN] [--capability-profile trusted|sandboxed] [--no-fs] [--fs-root PATH] [--fs-readonly] [--no-http] [--allow-process] [--process-root PATH] [--allow-pty] [--no-tui] [--allow-tui] [--no-webview] [--allow-webview] [--no-env] [--env-allow NAME] [--no-sleep] [--http-allow-host HOST] [--allow-sockets] [--socket-allow-host HOST] [path]",
        "`$task task_status",
        "`$task info",
        "`$task release_task",
        "tui_read_key value",
        "`$body `$state `$actions webview_window_state value",
        "`"Increment`" `"increment`" webview_button",
        "`"Increment`" `"increment`" `"increment_counter`" webview_action",
        "webview_window_state",
        "tasks count",
        "fs_read_text",
        "fs_delete",
        "workspace_read_text",
        "workspace_list",
        "workspace_delete",
        "http_get",
        "http_get_task",
        "tcp_listen",
        "tcp_accept",
        "tcp_listener_release",
        "tcp_connect",
        "tcp_read",
        "tcp_release",
        "ws_listen",
        "ws_accept",
        "ws_listener_release",
        "ws_connect",
        "ws_read",
        "ws_release",
        "process_spawn",
        "process_start",
        "process_read",
        "process_release",
        "pty_start",
        "pty_read",
        "pty_release",
        "timestamp_parse",
        "timestamp_format",
        "date_parse",
        "date_format",
        "duration_hours",
        "approval_create",
        "approval_claim",
        "result_envelope",
        "runtime_capabilities",
        "tui_write",
        "{ `$user name.get }",
        "{% show get if %}",
        "{% users get &quot;user&quot; each %}",
        "{% &quot;Featured users&quot; &quot;heading&quot; var do %}"
    )

    foreach ($example in $requiredExamples) {
        if (-not $index.Contains($example) -and -not $app.Contains($example) -and -not $webAndDataGuide.Contains($example)) {
            $failures.Add("Docs are missing example text: $example")
        }
    }

    $requiredCss = @(
        "--ink",
        ".word-grid",
        ".stack-rail",
        "@media"
    )

    foreach ($marker in $requiredCss) {
        if (-not $styles.Contains($marker)) {
            $failures.Add("styles.css is missing marker: $marker")
        }
    }

    if (-not $readme.Contains("Open index.html")) {
        $failures.Add("README.md does not explain how to open the static site")
    }
}

if ($failures.Count -gt 0) {
    foreach ($failure in $failures) {
        Write-Error $failure
    }
    exit 1
}

Write-Host "Ricochet reference docs validation passed."
